### ISSUE TITLE
Error in method: GetEntry, error code: -2146233036 Assembly Version: 1.0.0.30301

### ISSUE THREAD

**Issue by SneakyTactician** [SneakyTactician/SomeCardGames#92]
Exception:
Error code: -2146233036
Error message: The type initializer for 'SomeCardGamesAPI.API.Language.TheDictionary' threw an exception.
Exception hash code: 28840036
Help link: 
Method: GetEntry
Method hash code: 12197122
Source: SomeCardGamesAPI

Stack trace: 
   at SomeCardGamesAPI.API.Language.TheDictionary.GetEntry(Int32 Line)
   at Golf.Code.UI_s.WinForms.NewGolfForm.NewGolfForm_Load(Object sender, EventArgs e) in C:\Users\Sneak_000\Source\Repos\SomeCardGames\SomeCardGames\Golf\Code\UI's\WinForms\NewGolfForm.cs:line 38

Type: System.TypeInitializationException

Inner Exceptions: 
Inner Exception # 1:
Error code: -2147467261
Error message: Value cannot be null.
Parameter name: collection
Method: .ctor
Source: mscorlib

Stack trace: 
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at SomeCardGamesAPI.API.Language.TheDictionary..cctor() in C:\Users\Sneak_000\Source\Repos\SomeCardGames\SomeCardGames\SomeCardGamesAPI\API\Language\TheDictionary.cs:line 31

Type: System.ArgumentNullException

Method data:

Object: Name
.ctor

Object: MemberType
Constructor

Object: DeclaringType
System.Collections.Generic.List`1[T]

Object: ReflectedType
System.Collections.Generic.List`1[T]

Object: MetadataToken
100677788

Object: Module
CommonLanguageRuntimeLibrary

Object: MethodHandle
System.RuntimeMethodHandle

Object: Attributes
PrivateScope, Public, HideBySig, SpecialName, RTSpecialName

Object: CallingConvention
Standard, HasThis

Object: IsSecurityCritical
False

Object: IsSecuritySafeCritical
False

Object: IsSecurityTransparent
True

Object: ContainsGenericParameters
True

Object: MethodImplementationFlags
IL

Object: IsGenericMethodDefinition
False

Object: IsGenericMethod
False

Object: IsPublic
True

Object: IsPrivate
False

Object: IsFamily
False

Object: IsAssembly
False

Object: IsFamilyAndAssembly
False

Object: IsFamilyOrAssembly
False

Object: IsStatic
False

Object: IsFinal
False

Object: IsVirtual
False

Object: IsHideBySig
True

Object: IsAbstract
False

Object: IsSpecialName
True

Object: IsConstructor
True

Object: CustomAttributes
System.Collections.ObjectModel.ReadOnlyCollection`1[System.Reflection.CustomAttributeData]

Other data:

Object: Count
0

Object: Keys
System.Collections.ListDictionaryInternal+NodeKeyValueCollection

Object: IsReadOnly
False

Object: IsFixedSize
False

Object: IsSynchronized
False

Object: SyncRoot
System.Object

Object: Values
System.Collections.ListDictionaryInternal+NodeKeyValueCollection

System information:
Is 64 bit OS: True
Is 64 bit process: False
OS version: Microsoft Windows NT 6.2.9200.0
Processor count: 8
System page size: 4096
Common Language Runtime version: 4.0.30319.42000

Some Card Games application information: 
Handles: 348
Non paged system memory: 36424
Paged memory: 281042944
Max memory usage: 302526464
Is responding: True
Threads running: 17
Screen Size: {Width=2560, Height=1440}

**Comment by SneakyTactician** [comment]
Could not reproduce.
